---
  title: "project_information"
author: "Omer Ozeren"
date: "12/05/2019"
output: md_document
---
  
  
  Title: Analysis Of Suicide Rate Among Different Cohorts Globally 

Author: Olga Shiligin 

GitHub (link to the project): <https://github.com/olgashiligin/data608/tree/master/final_project>
  
  Shinyapps (link to the deployed project): https://olgashiligin.shinyapps.io/suicide_study/
  
  Course: Knowledge and Visual Analytics (Data 608)

Purpose 
--------
  The purpose of the project is to find signals correlated to
increased suicide rates among different cohorts globally.

Visualization
--------------
  
  The project includes the following aspects of the Analysis of Global
Suicide Rate:
  
  -  Correlation of suicide rate and GDP per capita by country and in aggregationfrom 1985
to 2016 years.

-  Dynamic profile of suicides by country from 1985 to 2016 years (animation added).

-  Suicide rate distribution by country (World Choropleth Map).

Insights
---------
  
  -  Suicide rate shows decreasing trend globally.

-  There is no strong correlation between suicide rate and GDP per capita. However several countries have some kind of negative correlation between suicide rate and GDP per capita.

-  The dominant suicide age group is 75 + years, the dominant sex group - men.

-  Women's suicide rate significantly lower than man's suicide rate.

-  The highest suicide rate is in Lithuania - 40, the rest countries in the list of the countries with the highest suicide rate are developing northern countries (except Sri Lanka).

Limitations
-----------
  
  Suicide rate statistics is not available for several countries.


Visualization Tools Used: Shiny App, Plotly API, R

Terminology Used:
  
  - GDP per Capita - is a measure of a country's economic output that
accounts for its number of people. It divides the country's gross
domestic product by its total population.

- Suicide Rate - number of suicides per 100k of population.

Possible Further Analysis: correlation of number of sunny days per year vs suicide rate by country.

Data Sources
-------------
  
  <https://www.kaggle.com/russellyates88/suicide-rates-overview-1985-to-2016>
  
  <http://hdr.undp.org/en/indicators/137506>
  
  <http://databank.worldbank.org/data/source/world-development-indicators#>

<https://www.kaggle.com/szamil/suicide-in-the-twenty-first-century/notebook>
  
  <http://www.who.int/mental_health/suicide-prevention/en/>
  
  References
-----------
  
  <https://plot.ly/r/animations/>
  
  <https://stackoverflow.com/questions/31914161/how-to-convert-rmd-into-md-in-r-studio>
  
  <https://plotly-r.com/animating-views.html>
  
  https://www.youtube.com/watch?v=VQdA7XoA-lY

https://beta.rstudioconnect.com/content/2671/Combining-Shiny-R-Markdown.html

https://stackoverflow.com/questions/36472001/call-a-rmarkdown-report-in-the-shiny-application/36476563#36476563
